# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vggiTvqLdyj9uuXCHiFq49mWZ7UVoQMY
"""

import pandas as pd
import numpy as numpy
url = "https://raw.githubusercontent.com/omprakashpatna18-del/Capstone-Project/main/Exam_Score_Prediction.csv"

data = pd.read_csv(url)
print(data.head())



import uvicorn
import joblib

import google.genai as genai

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel





columns=data.columns

#select features and target arrays
target=data["exam_score"]
feature_data=data.drop(["student_id","exam_score"],axis=1)

#split training and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(feature_data,target,random_state=1,test_size=0.25)

cat_cols=['gender','course','internet_access','sleep_quality','study_method','facility_rating','exam_difficulty']

for i in X_train.columns:
    if i in cat_cols:
     print(X_train[i].unique())

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()


# Encode categorical features
for col in X_train.select_dtypes(include='object').columns:

    X_train[col] = le.fit_transform(X_train[col])
    X_test[col]=le.transform(X_test[col])

X_train.head()
for i in X_train.columns:
    if i in cat_cols:
        print(X_train[i].unique())

X_test.dtypes

#fit a model to the data
import xgboost as xgb

# Train a model using the scikit-learn API
xgb_regressor = xgb.XGBRegressor(n_estimators=500, objective='reg:squarederror', tree_method='hist', eta=0.05, max_depth=4, enable_categorical=False,reg_alpha=40,min_child_weight=40,gamma=10,reg_lambda=10)
xgb_regressor.fit(X_train, y_train,verbose=True)

print(type(xgb_regressor))

pred=xgb_regressor.predict(X_test)
print(pred)



from sklearn.metrics import mean_squared_error,mean_absolute_percentage_error

# Calculate MSE using the built-in function
mse = mean_squared_error(y_test, pred)
mape=mean_absolute_percentage_error(y_test,pred)

print(f"Mean Squared Error (Scikit-learn): {mse}")
print(mape)

joblib.dump(xgb_regressor, 'xgb_model.joblib')

model = joblib.load("xgb_model.joblib")
class StudentData(BaseModel):
    age: int
    gender: str
    course: str
    study_hours: float
    class_attendance: float
    internet_access: str
    sleep_hours: float
    sleep_quality: str
    study_method: str
    facility_rating: str
    exam_difficulty: str

FEATURE_COLUMNS = [
      'age', 'gender', 'course', 'study_hours', 'class_attendance',
          'internet_access', 'sleep_hours', 'sleep_quality',
              'study_method', 'facility_rating', 'exam_difficulty'
]

master_map= {
      'gender': {'male': 0, 'female': 1, 'other': 2},
      'course': {'b.tech': 2, 'bca': 5, 'b.sc': 1, 'bba': 4, 'diploma': 6,'b.com':0,'ba':3},
      'internet_access': {'yes': 1, 'no': 0},
      'sleep_quality': {'poor': 2, 'average': 0, 'good': 1},
      'study_method': {'self-study':4,'group study':1,'coaching':0,'online videos':3,'mixed':2},
      'facility_rating': {'low': 1, 'medium': 0, 'high': 2},
      'exam_difficulty': {'easy': 0, 'moderate': 2, 'hard': 1},
                              }
import os
import google.genai as genai
gemini_model=genai.Client(api_key=os.environ.get('GEMINI_API_KEY'))

def predict_marks(data):
    """
    Takes raw input from HTML form, encodes it exactly
    like your notebook, and returns XGBoost prediction.
    """

    # Build raw input dict (student_id excluded)
    raw = {
        'age'             : int(data.get('age', 20)),
        'gender'          : str(data.get('gender', 'male')).lower().strip(),
        'course'          : str(data.get('course', 'b.tech')).lower().strip(),
        'study_hours'     : float(data.get('study_hours', 5)),
        'class_attendance': float(data.get('class_attendance', 75)),
        'internet_access' : str(data.get('internet_access', 'yes')).lower().strip(),
        'sleep_hours'     : float(data.get('sleep_hours', 7)),
        'sleep_quality'   : str(data.get('sleep_quality', 'average')).lower().strip(),
        'study_method'    : str(data.get('study_method', 'mixed')).lower().strip(),
        'facility_rating' : str(data.get('facility_rating', 'medium')).lower().strip(),
        'exam_difficulty' : str(data.get('exam_difficulty', 'moderate')).lower().strip(),
    }

    df = pd.DataFrame([raw], columns=FEATURE_COLUMNS)

    # Apply same encoding as your notebook
    for col, mapping in master_map.items():
        if col in df.columns:
            val = str(df[col].iloc[0]).lower().strip()
            df[col] = mapping.get(val, 0)

    # Convert all to correct dtypes
    df = df.astype({
        'age'             : 'int64',
        'gender'          : 'int64',
        'course'          : 'int64',
        'study_hours'     : 'float64',
        'class_attendance': 'float64',
        'internet_access' : 'int64',
        'sleep_hours'     : 'float64',
        'sleep_quality'   : 'int64',
        'study_method'    : 'int64',
        'facility_rating' : 'int64',
        'exam_difficulty' : 'int64',
    })

    # Predict
    prediction = xgb_regressor.predict(df)[0]
    predicted_marks = round(float(prediction), 2)


    return predicted_marks

def features_ranked(data):
    """
    Takes raw input from HTML form, encodes it exactly
    like your notebook, and returns XGBoost prediction.
    """

    # Build raw input dict (student_id excluded)
    raw = {
        'age'             : int(data.get('age', 20)),
        'gender'          : str(data.get('gender', 'male')).lower().strip(),
        'course'          : str(data.get('course', 'b.tech')).lower().strip(),
        'study_hours'     : float(data.get('study_hours', 5)),
        'class_attendance': float(data.get('class_attendance', 75)),
        'internet_access' : str(data.get('internet_access', 'yes')).lower().strip(),
        'sleep_hours'     : float(data.get('sleep_hours', 7)),
        'sleep_quality'   : str(data.get('sleep_quality', 'average')).lower().strip(),
        'study_method'    : str(data.get('study_method', 'mixed')).lower().strip(),
        'facility_rating' : str(data.get('facility_rating', 'medium')).lower().strip(),
        'exam_difficulty' : str(data.get('exam_difficulty', 'moderate')).lower().strip(),
    }

    df = pd.DataFrame([raw], columns=FEATURE_COLUMNS)

    # Apply same encoding as your notebook
    for col, mapping in master_map.items():
        if col in df.columns:
            val = str(df[col].iloc[0]).lower().strip()
            df[col] = mapping.get(val, 0)

    # Convert all to correct dtypes
    df = df.astype({
        'age'             : 'int64',
        'gender'          : 'int64',
        'course'          : 'int64',
        'study_hours'     : 'float64',
        'class_attendance': 'float64',
        'internet_access' : 'int64',
        'sleep_hours'     : 'float64',
        'sleep_quality'   : 'int64',
        'study_method'    : 'int64',
        'facility_rating' : 'int64',
        'exam_difficulty' : 'int64',
    })

    # Predict
    prediction = xgb_regressor.predict(df)[0]
    predicted_marks = round(float(prediction), 2)

    # Feature importance (same as your notebook)
    importances = xgb_regressor.feature_importances_
    all_features_ranked = sorted(
        zip(importances, FEATURE_COLUMNS), reverse=True
    )

    return all_features_ranked



def get_suggestion(data, student_score, all_features_ranked):
    """
    Uses your exact same Gemini prompt from the notebook.
    """

    features_summary = "\n".join(
        [f"{name}: {val:.4f}" for val, name in all_features_ranked]
    )

    prompt_text = f"""
Predicted Marks: {student_score:.2f}%
Impact Factors:
{features_summary}

Task: Give a proper feedback to student in English. Keep it precise and straight to the point. Give suggestions to improve their marks. Do not hallucinate and predict marks.
Do not encourage the student to study for very long or short hours. Do not advise him/her to sleep too much or too little.
If you find the predicted marks more than 100 or class attendance more than 100, declare the data as invalid and tell the user to enter correct details.
Follow the given format:
1. Strengths
2. Areas to be Improved
3. Precautions
4. Suggestions
5. Overall Feedback
"""

    response = gemini_model.client.models.generate_content(prompt=prompt_text,model="gemini-2.0-flash",)
    return response.text



app = FastAPI(title="Student Marks Predictor")

# CORS — HTML pages ko allow karo
app.add_middleware(
CORSMiddleware,
allow_origins=["*"],
allow_methods=["*"],
allow_headers=["*"],
                )

@app.post("/api/predict")
async def predict(data: StudentData):
    marks = predict_marks(data.dict())  # Aapka existing function
    return {"predicted_marks": round(float(marks), 2)}
async def features_ranked(data:StudentData):
    features_ranked=suggestions(data.dict())
    return {"features":features_ranked }
@app.post("/api/suggest")
async def suggest(data: dict):
    marks = data["marks"]
    student = data["student_data"]
    features=features_ranked(data:dict())
    features_summary=".join(
        [f"{name}: {val:.4f}" for val, name in all_features_ranked]
    )

    prompt = f"""You are a helpful academic mentor. A student has received a predicted score of {marks}/100.

Student Profile:
- Age: {student['age']}
- Gender: {student['gender']}
- Course: {student['course']}
- Study Hours per day: {student['study_hours']}
- Class Attendance: {student['class_attendance']}%
- Internet Access: {student['internet_access']}
- Sleep Hours: {student['sleep_hours']}
- Sleep Quality: {student['sleep_quality']}
- Study Method: {student['study_method']}
- Facility Rating: {student['facility_rating']}
- Exam Difficulty: {student['exam_difficulty']}

Impact Factors:
{features_summary}

Task: Give a proper feedback to student in English. Keep it precise and straight to the point. Give suggestions to improve their marks. Do not hallucinate and predict marks.
Do not encourage the student to study for very long or short hours. Do not advise him/her to sleep too much or too little.
If you find the predicted marks more than 100 or class attendance more than 100, declare the data as invalid and tell the user to enter correct details.
Follow the given format:
1. Strengths
2. Areas to be Improved
3. Precautions
4. Suggestions
5. Overall Feedback
"""

    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=prompt
    )
    return response.text
